databases:
  - name: mongodb
    databaseName: orbit
    user: orbituser
    password: OrbitPass123!
    ipAllowList: ["0.0.0.0/0"]

services:
  - type: web
    name: orbit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://orbituser:OrbitPass123!@orbit-cluster.4bi15tv.mongodb.net/?retryWrites=true&w=majority&appName=orbit-cluster"
      - key: PORT
        value: 8000